### ISSUE TITLE
Create sentry key (DSN)?

### ISSUE THREAD

**Issue by mwarkentin** [jianyuan/terraform-provider-sentry#14]
It'd be great if we could also create a sentry key for a project during creation, in order to provide it in an output.

They provide APIs to create/list/delete keys:

* https://docs.sentry.io/api/projects/post-project-keys/
* https://docs.sentry.io/api/projects/get-project-keys/
* https://docs.sentry.io/api/projects/delete-project-key-details/

I suppose this would probably be it's own resource rather than being part of the project.

**Comment by mwarkentin** [comment]
Alternatively, a data source to get a list of keys by projects would probably work for us as well, as projects have a `default` key created along with the project automatically.

**Comment by jianyuan** [comment]
@mwarkentin I prefer to have 1 to 1 correspondence between the API resource endpoints and Terraform resources.

The data source is a good idea. I will implement this sometime this week.

**Comment by mwarkentin** [comment]
@jianyuan Agreed, after looking at the API, I think it would make most sense as a separate `sentry_project_key`. Looking forward to it!

**Comment by jianyuan** [comment]
At the moment, Terraform's data source does not support returning multiple entities.

In Sentry, a key is differentiated by its name and ID.

I think I found a good compromise: If there's only 1 project key, which is the case when a project is newly created, then the project key name or ID is optional. Otherwise, the data source should error and notify the user to add appropriate filtering.

**Comment by mwarkentin** [comment]
That sounds reasonable to me!

**Comment by mwarkentin** [comment]
Thanks!
