### ISSUE TITLE
Sentry issue alert conditions, filters, and actions in JSON string format reduce the usability and maintainability of the code

### ISSUE THREAD

**Issue by ryanbratten** [jianyuan/terraform-provider-sentry#379]
Up until version 0.12 we have been able to do things like this to populate the conditions, filters and actions fields of a sentry_issue_alert:
```
actions = [
    for channel in var.slack_channels:
    {
      id        = "sentry.integrations.slack.notify_action.SlackNotifyServiceAction"
      channel   = channel
      workspace = data.sentry_organization_integration.slack.internal_id
    }
  ]
```
We had intended to upgrade to version 0.12+ to use the new project inbound data filter resource however we will no longer be doing so due to the JSON string format change of the conditions, filters and actions. 

This change means the above code now needs to be refactored like so:
```
  actions = <<EOF
  [
    %{for i, channel in var.slack_channels}
    {
      "id": "sentry.integrations.slack.notify_action.SlackNotifyServiceAction",
      "channel": "${channel}",
      "workspace":  "${data.sentry_organization_integration.slack.internal_id}"
    }
    %{ if i < length(var.slack_channels) - 1 }, %{ endif }
    %{endfor}
  ]
EOF
```

This is not clean code nor is it maintainable. The IDE is unable to syntax highlight any of this and it will lead to more problems in the future as not all terraform features can be used with an EOF block

I understand the need to match the sentry API however in my opinion this should be the work of the provider to take in valid terraform (not EOF) and transform this to the contract of the sentry API

Please can we go back to valid terraform syntax instead of using EOF blocks?

**Comment by jianyuan** [comment]
Hello @ryanbratten, thank you for your suggestion. I value your input. I chose the JSON approach primarily due to the diverse nature of the configuration items. For instance, for the same property name, the value can vary between a string and an integer, depending on the type of configuration item. Take `targetIdentifier` as an example. According to the documentation:

> targetIdentifier: The ID of the target. This must be an integer for PagerDuty and Sentry apps, and a string for all others. Examples of appropriate values include a Slack channel name (#my-channel), a user ID, a team ID, a Sentry app ID, etc.

Due to Terraform's limitations, it's impractical to use the same property name for a union type (e.g., string and integer). Consequently, we would need to name these properties explicitly, such as `pageduty_id`, `sentry_app_id`, etc., with the appropriate types.

Alternatively, we could consider creating a data source for each condition, filter, and action that outputs JSON. A prime example is AWS's [iam_policy_document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document), which generates a policy JSON that can be used with [iam_policy.policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy#example-usage). We could adopt a similar approach and not introduce another incompatible change. Whenever a new configuration item is introduced, users can manually create the JSON and immediately use the new functionality while the data source that generates the JSON can be developed.

For the time being, I recommend using Terraform's `jsonencode()` function to construct your JSON. In your case, you can utilize Terraform arrays with `jsonencode()` to maintain HCL highlighting and facilitate the translation of Terraform language into JSON effectively.

```tf
actions = jsonencode([
    for channel in var.slack_channels:
    {
      id        = "sentry.integrations.slack.notify_action.SlackNotifyServiceAction"
      channel   = channel
      workspace = data.sentry_organization_integration.slack.internal_id
    }
])
```

I hope this helps!

**Comment by strugee** [comment]
> For the time being, I recommend using Terraform's `jsonencode()` function to construct your JSON.

Note that the docs say to avoid `jsonencode()` due to the int/float problem: https://registry.terraform.io/providers/jianyuan/sentry/latest/docs/resources/issue_alert

Are you suggesting that `parseint()` can make this safe? I'm also unclear on how that's even a problem because I can't imagine floats are being used as as identifiers (and JSON itself also cannot distinguish between ints and floats)?

**Comment by jianyuan** [comment]
Please continue in https://github.com/jianyuan/terraform-provider-sentry/issues/529.
