### ISSUE TITLE
Wants to create resource when token has no permission to view

### ISSUE THREAD

**Issue by charlesverdad** [jianyuan/terraform-provider-sentry#57]
I have a `*.tf` file with a `sentry_team` resource.

After creating the team using terraform, If I use a SENTRY_TOKEN with no permission to read teams, then the provider assumes the team doesn't exist and wants to create a new one.

Took me a while to figure out that the problem was a permissions scope thing. I'd expected the provider to output something like a 403 error instead of silently failing.

**Comment by mwarkentin** [comment]
Just a hunch, but this might be an issue with the way the sentry api responds if you don't have permission to view an object (a team in this case) - often APIs will return a `404` instead of a `403` error if you're missing permissions so that it doesn't expose if a team exists or not to anyone who tries to check. It does probably make it tricky to handle nicely in the terraform provider (the github provider has similar issues if your token isn't configured correctly).

**Comment by jianyuan** [comment]
Fixed in #70.
